version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    # Add these commands to fix permissions
    command: >
      bash -c "
        chmod 600 /var/lib/rabbitmq/.erlang.cookie || true;
        chown rabbitmq:rabbitmq /var/lib/rabbitmq/.erlang.cookie || true;
        docker-entrypoint.sh rabbitmq-server
      "
