"""empty message

Revision ID: 2b126c7c0676
Revises:
Create Date: 2025-03-01 22:02:37.612224

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b126c7c0676"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetups",
        sa.Column("meetup_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("rating", sa.DECIMAL(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("finish_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "STARTED", "COMING", name="meetupstatus"),
            nullable=False,
        ),
        sa.Column(
            "moderation_status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="moderationstatus"),
            nullable=False,
        ),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("meetup_id"),
    )
    op.create_table(
        "outbox",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_table(
        "reviews",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("meetup_id", sa.UUID(), nullable=False),
        sa.Column(
            "moderation_status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="moderationstatus"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.DECIMAL(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["meetup_id"], ["meetups.meetup_id"]),
        sa.PrimaryKeyConstraint("review_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    op.drop_table("outbox")
    op.drop_table("meetups")
    # ### end Alembic commands ###
